# Global configuration settings for Alertmanager
global:
  resolve_timeout: 1m  # Time to wait before resolving alerts
  slack_api_url: ' ENTER_SLACK_WEBHOOK_ADDRESSS '  # Slack webhook URL for sending notifications

# Routing configuration
route:
  receiver: 'slack-notifications'  # Default receiver for alerts

# Receivers configuration
receivers:
  - name: 'slack-notifications'  # Name of the receiver
    slack_configs:
      - channel: '#dev-infra'  # Slack channel to send notifications to
        send_resolved: true  # Whether to send a notification when an alert is resolved
        icon_url: https://avatars3.githubusercontent.com/u/3380462  # Icon URL for the Slack message
        title: |-  # Title template for Slack messages
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-  # Text template for Slack messages
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
